### ISSUE TITLE
Timelapse creating problem 

### ISSUE THREAD

**Issue by ThomasTom86** [motioneye-project/motioneye#2461]
Hello!  I get the following error message when creating a timelapse video!

best regards 
![4283AC0C-07C9-4685-A1B7-6E8F2BDE6D22](https://user-images.githubusercontent.com/75570143/166518960-40fecbbe-8925-4dd3-9df4-5d51413d9974.jpeg)
![2BBEC54D-2D79-45ED-86D2-6E94BAF965CB](https://user-images.githubusercontent.com/75570143/166518967-bb5faadf-f351-40ae-9421-ad380520e279.jpeg)
![228C1FD7-9C6A-4684-8B92-6F706CBAADE1](https://user-images.githubusercontent.com/75570143/166518969-780d3217-41fc-4ce9-a507-31d37ec2be26.jpeg)

**Comment by MichaIng** [comment]
When did you install motionEye? We merged a fix for creating timelapse videos from pictures just recently: #2437

**Comment by ThomasTom86** [comment]
about a week ago.

**Comment by MichaIng** [comment]
The commit was merged 6 days ago. Please try to update motionEye via linked instructions.

**Comment by ThomasTom86** [comment]
i have updated to the last release 0.43.0 but creating the timelapse still doesn't work.

**Comment by MichaIng** [comment]
You followed the upgrade instructions, especially `--force-reinstall`? Also did you `systemctl restart motioneye` afterwards? If so, please post the service logs again:
```sh
journalctl -u motioneye
```

**Comment by ThomasTom86** [comment]
yes I did the update the same way

this is the log…
![Uploading A85FFFF5-6A99-4C50-A4B4-8653CCC68A3F.jpeg…]()

**Comment by ThomasTom86** [comment]
![7A8DBDD8-B102-4B36-BF9F-71FD3540F2F9](https://user-images.githubusercontent.com/75570143/168535729-c660a626-2889-4900-b1d1-bd97735fbd21.jpeg)
![1911EE13-2251-442C-A105-C04232BB8135](https://user-images.githubusercontent.com/75570143/168535737-48272bef-d004-4a78-876a-90dc854cfb6a.jpeg)

**Comment by ThomasTom86** [comment]
yes I did the update the same way

this is the log ….
![F656FCE0-1C8A-4C0A-91C7-C29EE0CAF671](https://user-images.githubusercontent.com/75570143/168535998-584577fd-0abb-44e9-9b42-d0f9f7f136e0.jpeg)
![7EFEB041-BA14-4592-A986-4B6F0A0640CD](https://user-images.githubusercontent.com/75570143/168536011-88c1c95b-e0a2-4cad-923c-fb58c9622179.jpeg)
![60B8D2D3-4668-45C3-A37A-F4F52B5D0D88](https://user-images.githubusercontent.com/75570143/168536016-f1605f45-b70b-44ce-acd3-c33e0856f242.jpeg)
